name: "Podcast Generator - EHL"
author: "Emma Luk"
description: "Generates a feed for a podcast from a YAML file"
inputs:
  email:
    description: The committer's email address
    required: true
    default: ${{github.actor}}@localhost
  name:
    description: the committer's name
    required: true
    default: ${{github.actor}}
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.email }}
    - ${{ inputs.name }}
branding:
  icon: "git-branch"
  color: "red"
